kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: application-01-clusterrole-binding
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-sa
    namespace: gitops-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterrole-argocd
