apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-admin-app-02
  namespace: application-02  
subjects:
- kind: Group
  name: gitops-users  
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin-role-app-02 
  apiGroup: rbac.authorization.k8s.io
